## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID        City Country  Max Temp       Description      Lat       Lng  \
0        2       Alice      US     81.32        few clouds  27.7523  -98.0697   
1        3  Balikpapan      ID     76.19  scattered clouds  -1.2675  116.8289   
2        4       Aswan      EG     96.10         clear sky  24.0934   32.9070   
3        6  Viransehir      TR     79.54         clear sky  37.2353   39.7631   
4        7        Lebu      CL     51.67   overcast clouds -37.6167  -73.6500   

                                         Hotel Name  
0  Holiday Inn Express & Suites Alice, an IHG Hotel  
1                                   ibis Balikpapan  
2                                         Nuba Nile  
3                            Viranşehir Öğretmenevi  
4                                  Hostal Las Lilas

In [5]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""


# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [7]:
# 4a. Add a marker layer for each city to the map.
# 11a. Add a marker layer for each city to the map. 
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [26]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == 'Plouzane')]
vacation_end = vacation_df.loc[(vacation_df["City"] == 'Plouzane')]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == 'Chauny')]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == 'Reims')] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == 'Saint-Francois')] 
vacation_start

City_ID      City Country  Max Temp Description      Lat     Lng  \
222      298  Plouzane      FR     71.92   clear sky  48.3833 -4.6167   

                     Hotel Name  
222  Carrefour Voyages Plouzané

In [38]:
vacation_start[["Lat","Lng"]].to_numpy()

array([[48.3833, -4.6167]])

In [56]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()
end = vacation_end[["Lat", "Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()

print(start)
print(end)
print(stop1)
print(stop2)
print(stop3)

[[48.3833 -4.6167]]
[[48.3833 -4.6167]]
[[49.6151  3.2186]]
[[49.1667  4.0833]]
[[46.4154  3.9054]]


In [59]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

start = (48.38, -4.61)
end = (48.38, -4.61)
stop1 = (49.61, 3.21)
stop2 =(49.16, 4.08)
stop3 = (46.41, 3.90)


fig = gmaps.figure()
start2end_via_stops = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode="DRIVING")
fig.add_layer(start2end_via_stops)
fig


Figure(layout=FigureLayout(height='420px'))

In [62]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID            City Country  Max Temp Description      Lat     Lng  \
0      298        Plouzane      FR     71.92   clear sky  48.3833 -4.6167   
1      607          Chauny      FR     66.61   clear sky  49.6151  3.2186   
2      506           Reims      FR     63.34   clear sky  49.1667  4.0833   
3      429  Saint-Francois      FR     59.41   clear sky  46.4154  3.9054   

                   Hotel Name  
0  Carrefour Voyages Plouzané  
1       Auberge De Villequier  
2            Château de Rilly  
3           Manoir Du Bonheur

In [66]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name} °F</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Description}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [1]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.0)
start2end_via_stops = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode="DRIVING")
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

NameError: name 'itinerary_df' is not defined